// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpd9LECZZ4cQ0cquozXTdh6WyWiMu0dAU',
    appId: '1:113679249713:web:0b4b2b53e7c02fe73e0010',
    messagingSenderId: '113679249713',
    projectId: 'fir-example-adf-7bad3',
    authDomain: 'fir-example-adf-7bad3.firebaseapp.com',
    storageBucket: 'fir-example-adf-7bad3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj_C8140vu2HNFUphn_zlYVOiqNErYtkk',
    appId: '1:113679249713:android:bb264f0c80c2ee203e0010',
    messagingSenderId: '113679249713',
    projectId: 'fir-example-adf-7bad3',
    storageBucket: 'fir-example-adf-7bad3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpj8lL-UJ5JK4kA0m_49zB0DncAKz-aSc',
    appId: '1:113679249713:ios:3275f7a44d89fdfb3e0010',
    messagingSenderId: '113679249713',
    projectId: 'fir-example-adf-7bad3',
    storageBucket: 'fir-example-adf-7bad3.appspot.com',
    iosBundleId: 'com.example.firebaseExample',
  );
}
